/*
https://leetcode.com/problems/find-the-difference/
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Find the sum of the ASCII values of all chars in t and subtract the sum from s.
Time - O(n)
Space - O(1)
*/

public class Solution {
    public char findTheDifference(String s, String t) {

        int charSum = (int) t.charAt(t.length() - 1);

        for (int i = 0; i < s.length(); ++i) {
            charSum += (int) t.charAt(i);
            charSum -= (int) s.charAt(i);
        }
        return (char) charSum;
    }
}